package com.allen.questionnaire.service.cache.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.allen.questionnaire.service.cache.db.bean.CacheEntity;

import com.allen.questionnaire.service.cache.db.CacheEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheEntityDaoConfig;

    private final CacheEntityDao cacheEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheEntityDaoConfig = daoConfigMap.get(CacheEntityDao.class).clone();
        cacheEntityDaoConfig.initIdentityScope(type);

        cacheEntityDao = new CacheEntityDao(cacheEntityDaoConfig, this);

        registerDao(CacheEntity.class, cacheEntityDao);
    }
    
    public void clear() {
        cacheEntityDaoConfig.clearIdentityScope();
    }

    public CacheEntityDao getCacheEntityDao() {
        return cacheEntityDao;
    }

}
